import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const abiDir = join(root, "../../contracts/abi");
const out = join(root, "../src/lib/abi.ts");

const contracts = ["KycRegistry", "ShardToken", "Offering", "IssuanceFactory", "HarvestRedemption"];
const lines = ["// Generated by scripts/sync-abi.mjs from contracts/abi. Do not edit by hand.", ""];

for (const name of contracts) {
  const abi = JSON.parse(readFileSync(join(abiDir, `${name}.json`), "utf8"));
  const id = name[0].toLowerCase() + name.slice(1);
  lines.push(`export const ${id}Abi = ${JSON.stringify(abi, null, 2)} as const;`, "");
}

lines.push(
  "export const erc20Abi = [",
  '  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint8" }] },',
  '  { type: "function", name: "symbol", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "string" }] },',
  '  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "account", type: "address" }], outputs: [{ name: "", type: "uint256" }] },',
  '  { type: "function", name: "allowance", stateMutability: "view", inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }], outputs: [{ name: "", type: "uint256" }] },',
  '  { type: "function", name: "approve", stateMutability: "nonpayable", inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ name: "", type: "bool" }] },',
  '  { type: "function", name: "mint", stateMutability: "nonpayable", inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }], outputs: [] },',
  "] as const;",
  ""
);

writeFileSync(out, lines.join("\n"));
console.log(`Wrote ${out}`);
